[package]
name = "treetop_tree_house"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
time = "0.3.17"
